// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingControll.Infra.Data.Contexts;

namespace ParkingControll.Infra.Data.Migrations
{
    [DbContext(typeof(ParkingContext))]
    [Migration("20200714200150_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ParkingControll.Domain.Features.PriceAggregation.Price", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Additional");

                    b.Property<DateTime>("Final");

                    b.Property<DateTime>("Initial");

                    b.Property<bool>("Removed");

                    b.Property<int>("Tolerance");

                    b.Property<decimal>("Value");

                    b.HasKey("Id");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("ParkingControll.Domain.Features.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AmountPaid");

                    b.Property<DateTime>("CameIn");

                    b.Property<DateTime?>("Exited");

                    b.Property<string>("Plate")
                        .IsRequired();

                    b.Property<decimal>("Price");

                    b.Property<bool>("Removed");

                    b.Property<string>("TotalTimeInParking");

                    b.Property<string>("TotalTimePaid");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
